import type { Exercise } from "./types";

export const EXERCISE_DATABASE: Exercise[] = [
  // ─── GLUTES (5) ───────────────────────────────────────────────────────────
  {
    id: "glute_001",
    nameEn: "Hip Thrust",
    nameAr: "دفع الورك",
    category: "glutes",
    primaryMuscles: ["gluteus maximus"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    cyclePhases: ["power", "clarity"],
    emoji: "🍑",
    descriptionEn: "A barbell loaded hip extension that maximally activates the glute max.",
    descriptionAr: "تمرين تمديد الورك بالبار لتنشيط عضلة الألية الكبرى بالكامل.",
    commonMistakesEn: ["Hyperextending the lower back at top", "Not driving through the heels"],
    commonMistakesAr: ["الإفراط في تقوس أسفل الظهر", "عدم الدفع بالكعبين"],
    breathingEn: "Exhale as you drive the hips up; inhale on the way down.",
    breathingAr: "ازفر عند رفع الوركين، وشهق عند النزول.",
    beginnerTipsEn: ["Start with bodyweight or a light resistance band", "Keep chin tucked"],
    beginnerTipsAr: ["ابدئي بوزن الجسم أو الإيلاستيك الخفيف", "اضغطي ذقنك للأسفل"],
    videoUrl: "",
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    demoImage: require("../../../assets/images/exercises/hip-thrust.png") as number,
    demoHint: "Drive hips powerfully upward against the barbell",
    isTimeBased: false,
    defaultSets: 4,
    defaultReps: 10,
    defaultDurationSec: 0,
  },
  {
    id: "glute_002",
    nameEn: "Glute Bridge",
    nameAr: "جسر الألية",
    category: "glutes",
    primaryMuscles: ["gluteus maximus"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["bodyweight", "resistance_band"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🌉",
    descriptionEn: "Bodyweight floor bridge that builds glute strength without equipment.",
    descriptionAr: "تمرين أرضي لتقوية الألية بدون معدات.",
    commonMistakesEn: ["Raising the hips too high", "Letting knees cave inward"],
    commonMistakesAr: ["رفع الوركين عالياً جداً", "انهيار الركبتين للداخل"],
    breathingEn: "Exhale on the bridge up, inhale on the way down.",
    breathingAr: "ازفر عند الرفع، وشهق عند النزول.",
    beginnerTipsEn: ["Squeeze glutes at the top for 2 seconds", "Keep feet hip-width apart"],
    beginnerTipsAr: ["اضغطي الألية لمدة ثانيتين في الأعلى", "ضعي قدميك بعرض الوركين"],
    videoUrl: "",
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    demoImage: require("../../../assets/images/exercises/glute-bridge.png") as number,
    demoHint: "Bridge hips up from the floor, squeeze glutes at the top",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultDurationSec: 0,
  },
  {
    id: "glute_003",
    nameEn: "Cable Kickback",
    nameAr: "الركلة الخلفية بالكابل",
    category: "glutes",
    primaryMuscles: ["gluteus maximus"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["cable"],
    difficulty: "beginner",
    cyclePhases: ["renewal", "power", "clarity"],
    emoji: "🔙",
    descriptionEn: "Single-leg cable extension isolating the glute max through full ROM.",
    descriptionAr: "تمديد ساق مفردة بالكابل لعزل عضلة الألية الكبرى.",
    commonMistakesEn: ["Swinging the torso", "Using too much weight"],
    commonMistakesAr: ["تأرجح الجذع", "استخدام وزن زائد"],
    breathingEn: "Exhale as you kick back.",
    breathingAr: "ازفر عند الركل للخلف.",
    beginnerTipsEn: ["Keep slight bend in standing knee", "Squeeze at full extension"],
    beginnerTipsAr: ["ابقي انحناء خفيف في ركبة الوقوف", "اضغطي الألية عند الامتداد الكامل"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultDurationSec: 0,
  },
  {
    id: "glute_004",
    nameEn: "Sumo Deadlift",
    nameAr: "الرفعة الأرضية السومو",
    category: "glutes",
    primaryMuscles: ["gluteus maximus", "adductors"],
    secondaryMuscles: ["hamstrings", "lower back", "core"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    cyclePhases: ["power", "clarity"],
    emoji: "🏋️",
    descriptionEn: "Wide-stance deadlift emphasizing glutes and inner thighs.",
    descriptionAr: "رفعة أرضية بموقف واسع تركز على الألية والخصر الداخلي.",
    commonMistakesEn: ["Rounding the upper back", "Knees caving in at the floor"],
    commonMistakesAr: ["تقوس الظهر العلوي", "انهيار الركبتين عند الأرض"],
    breathingEn: "Big breath in before the pull; exhale at lockout.",
    breathingAr: "شهق كبير قبل الشد؛ ازفر عند الإقفال.",
    beginnerTipsEn: ["Practice with a light trap bar first", "Drive knees out over toes"],
    beginnerTipsAr: ["تدربي أولاً بشريط خفيف", "ادفعي الركبتين للخارج فوق أصابع القدم"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 4,
    defaultReps: 6,
    defaultDurationSec: 0,
  },
  {
    id: "glute_005",
    nameEn: "Banded Clamshell",
    nameAr: "فتحة الصدفة بالإيلاستيك",
    category: "glutes",
    primaryMuscles: ["gluteus medius"],
    secondaryMuscles: ["hip external rotators"],
    equipment: ["resistance_band"],
    difficulty: "beginner",
    cyclePhases: ["menstrual", "calm", "all"],
    emoji: "🦀",
    descriptionEn: "Side-lying external rotation activating the often-neglected glute medius.",
    descriptionAr: "دوران خارجي جانبي لتنشيط الألية الوسطى المهملة.",
    commonMistakesEn: ["Rolling the pelvis back", "Not controlling the return"],
    commonMistakesAr: ["إمالة الحوض للخلف", "عدم التحكم في العودة"],
    breathingEn: "Exhale on the open, inhale on the close.",
    breathingAr: "ازفر عند الفتح، وشهق عند الإغلاق.",
    beginnerTipsEn: ["Keep hips stacked", "Move only at the hip, not the pelvis"],
    beginnerTipsAr: ["ابقي الوركين فوق بعض", "تحركي من الورك فقط، وليس من الحوض"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultDurationSec: 0,
  },

  // ─── LEGS (5) ──────────────────────────────────────────────────────────────
  {
    id: "legs_001",
    nameEn: "Barbell Back Squat",
    nameAr: "القرفصاء الخلفية بالبار",
    category: "legs",
    primaryMuscles: ["quadriceps", "gluteus maximus"],
    secondaryMuscles: ["hamstrings", "core", "adductors"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    cyclePhases: ["power", "clarity"],
    emoji: "🏋️‍♀️",
    descriptionEn: "Foundational lower-body compound movement targeting quads and glutes.",
    descriptionAr: "الحركة المركبة الأساسية للجزء السفلي تستهدف الرباعية والألية.",
    commonMistakesEn: ["Knees caving inward", "Good morning squat (torso too forward)"],
    commonMistakesAr: ["انهيار الركبتين للداخل", "ميل الجذع للأمام كثيراً"],
    breathingEn: "Valsalva breath in before the descent; exhale on the ascent.",
    breathingAr: "شهق فالسالفا قبل النزول؛ ازفر عند الصعود.",
    beginnerTipsEn: ["Squat to a box to learn depth", "Push the floor away with your heels"],
    beginnerTipsAr: ["اقرفصي فوق كرسي لتتعلمي العمق", "ادفعي الأرض بعيداً بكعبيك"],
    videoUrl: "",
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    demoImage: require("../../../assets/images/exercises/squat.png") as number,
    demoHint: "Descend deep, then drive through heels to stand",
    isTimeBased: false,
    defaultSets: 4,
    defaultReps: 8,
    defaultDurationSec: 0,
  },
  {
    id: "legs_002",
    nameEn: "Bulgarian Split Squat",
    nameAr: "القرفصاء المنفردة البلغارية",
    category: "legs",
    primaryMuscles: ["quadriceps", "gluteus maximus"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["dumbbell"],
    difficulty: "intermediate",
    cyclePhases: ["renewal", "power", "clarity"],
    emoji: "🦵",
    descriptionEn: "Single-leg squat variant with rear foot elevated, fixing imbalances.",
    descriptionAr: "قرفصاء أحادية القدم مع رفع القدم الخلفية، تصحح اختلالات القوة.",
    commonMistakesEn: ["Front knee tracking past the toes", "Losing balance due to stance too narrow"],
    commonMistakesAr: ["امتداد الركبة الأمامية أمام أصابع القدم", "فقدان التوازن بسبب ضيق القدمين"],
    breathingEn: "Inhale down, exhale up.",
    breathingAr: "شهق للأسفل، ازفر للأعلى.",
    beginnerTipsEn: ["Start with bodyweight before adding load", "Keep torso upright"],
    beginnerTipsAr: ["ابدئي بوزن الجسم قبل إضافة الحمل", "اجعلي جذعك مستقيماً"],
    videoUrl: "",
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    demoImage: require("../../../assets/images/exercises/bulgarian-split-squat.png") as number,
    demoHint: "Lower body with front leg bearing the weight",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultDurationSec: 0,
  },
  {
    id: "legs_003",
    nameEn: "Leg Press",
    nameAr: "ضغط الساق بالآلة",
    category: "legs",
    primaryMuscles: ["quadriceps", "gluteus maximus"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["machine"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🔩",
    descriptionEn: "Machine-based quad and glute press with less spinal loading.",
    descriptionAr: "ضغط الرباعية والألية بالآلة مع ضغط أقل على العمود الفقري.",
    commonMistakesEn: ["Letting lower back lift off the pad", "Locking out knees completely"],
    commonMistakesAr: ["رفع أسفل الظهر عن الوسادة", "تثبيت الركبتين بالكامل"],
    breathingEn: "Exhale as you press out.",
    breathingAr: "ازفر عند الضغط للخارج.",
    beginnerTipsEn: ["Never lock out the knees", "Place feet shoulder-width for balance"],
    beginnerTipsAr: ["لا تثبتي الركبتين أبداً", "ضعي القدمين بعرض الكتفين للتوازن"],
    videoUrl: "",
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    demoImage: require("../../../assets/images/exercises/leg-press.png") as number,
    demoHint: "Press platform away through both feet",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultDurationSec: 0,
  },
  {
    id: "legs_004",
    nameEn: "Nordic Hamstring Curl",
    nameAr: "ثني أوتار الركبة النوردية",
    category: "legs",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["calves", "core"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    cyclePhases: ["power"],
    emoji: "💪",
    descriptionEn: "Eccentric hamstring exercise with best injury prevention evidence.",
    descriptionAr: "تمرين مركيز لأوتار الركبة مع أقوى دليل على الوقاية من الإصابات.",
    commonMistakesEn: ["Going too fast eccentrically", "Collapsing at the hips"],
    commonMistakesAr: ["السرعة الزائدة في الجزء المركيز", "انهيار الوركين"],
    breathingEn: "Exhale as you lower; inhale as you return.",
    breathingAr: "ازفري عند النزول؛ وشهقي عند العودة.",
    beginnerTipsEn: ["Use hands to assist on the way up", "3-second lowering tempo"],
    beginnerTipsAr: ["استخدمي يديك للمساعدة في الصعود", "وتيرة 3 ثوانٍ للنزول"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 5,
    defaultDurationSec: 0,
  },
  {
    id: "legs_005",
    nameEn: "Walking Lunge",
    nameAr: "التقدم المشترك المتحرك",
    category: "legs",
    primaryMuscles: ["quadriceps", "gluteus maximus"],
    secondaryMuscles: ["hamstrings", "calves", "core"],
    equipment: ["dumbbell", "bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["renewal", "clarity", "calm"],
    emoji: "🚶‍♀️",
    descriptionEn: "Dynamic alternating lunge pattern for lower body strength and coordination.",
    descriptionAr: "نمط تقدم بديل ديناميكي لقوة الجزء السفلي والتنسيق.",
    commonMistakesEn: ["Front knee going past toes", "Torso leaning forward"],
    commonMistakesAr: ["الركبة الأمامية تتجاوز أصابع القدم", "الجذع يميل للأمام"],
    breathingEn: "Exhale with each step forward.",
    breathingAr: "ازفري مع كل خطوة للأمام.",
    beginnerTipsEn: ["Take a long stride to protect the knee", "Keep your gaze forward"],
    beginnerTipsAr: ["خذي خطوة طويلة لحماية الركبة", "ابقي نظرك للأمام"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultDurationSec: 0,
  },

  // ─── CHEST (4) ─────────────────────────────────────────────────────────────
  {
    id: "chest_001",
    nameEn: "Barbell Bench Press",
    nameAr: "الضغط بالبار على المقعد المستوي",
    category: "chest",
    primaryMuscles: ["pectoralis major"],
    secondaryMuscles: ["anterior deltoid", "triceps"],
    equipment: ["barbell"],
    difficulty: "intermediate",
    cyclePhases: ["power", "clarity"],
    emoji: "🏋️",
    descriptionEn: "Classic upper-body compound pressing movement for chest strength.",
    descriptionAr: "حركة الضغط المركبة الكلاسيكية للجزء العلوي لتقوية الصدر.",
    commonMistakesEn: ["Bouncing the bar off the chest", "Flaring elbows too wide"],
    commonMistakesAr: ["ارتداد البار عن الصدر", "نشر المرفقين بشكل مفرط"],
    breathingEn: "Inhale before the descent; exhale on the press.",
    breathingAr: "شهق قبل النزول؛ ازفري عند الضغط.",
    beginnerTipsEn: ["Touch the lower chest, not the neck", "Drive legs into the floor"],
    beginnerTipsAr: ["المسي الصدر السفلي، وليس الرقبة", "ادفعي الساقين في الأرض"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 4,
    defaultReps: 8,
    defaultDurationSec: 0,
  },
  {
    id: "chest_002",
    nameEn: "Dumbbell Flye",
    nameAr: "فتح الصدر بالدمبل",
    category: "chest",
    primaryMuscles: ["pectoralis major"],
    secondaryMuscles: ["anterior deltoid"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    cyclePhases: ["renewal", "power", "clarity"],
    emoji: "🦅",
    descriptionEn: "Wide arc chest isolation exercise for inner chest development.",
    descriptionAr: "تمرين عزل الصدر بقوس واسع لتطوير الصدر الداخلي.",
    commonMistakesEn: ["Going too heavy and losing form", "Overextending at the bottom"],
    commonMistakesAr: ["استخدام وزن زائد مع فقدان الشكل", "الإفراط في الفتح في الأسفل"],
    breathingEn: "Inhale as arms open wide; exhale as you bring them back.",
    breathingAr: "شهق عند فتح الذراعين؛ وازفري عند الإغلاق.",
    beginnerTipsEn: ["Keep slight bend in elbows throughout", "Think 'hugging a tree'"],
    beginnerTipsAr: ["ابقي انحناء خفيف في المرفقين", "تخيلي أنك تعانقين شجرة"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultDurationSec: 0,
  },
  {
    id: "chest_003",
    nameEn: "Incline Dumbbell Press",
    nameAr: "الضغط بالدمبل على المقعد المائل",
    category: "chest",
    primaryMuscles: ["upper pectoralis major"],
    secondaryMuscles: ["anterior deltoid", "triceps"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    cyclePhases: ["renewal", "power"],
    emoji: "📐",
    descriptionEn: "Incline press targeting the upper chest for fuller appearance.",
    descriptionAr: "ضغط مائل يستهدف الصدر العلوي لمظهر أكثر اكتمالاً.",
    commonMistakesEn: ["Setting incline too steep (becomes shoulder press)", "Uneven lowering"],
    commonMistakesAr: ["إمالة المقعد بشكل مفرط يصبح ضغط كتف", "نزول غير متساوٍ"],
    breathingEn: "Inhale on the way down; exhale while pressing.",
    breathingAr: "شهق في الطريق للأسفل؛ ازفري عند الضغط.",
    beginnerTipsEn: ["30-45° is optimal incline angle", "Neutral grip reduces shoulder stress"],
    beginnerTipsAr: ["30-45° هي زاوية الإمالة المثلى", "القبضة المحايدة تقلل من ضغط الكتف"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultDurationSec: 0,
  },
  {
    id: "chest_004",
    nameEn: "Push-Up",
    nameAr: "تمرين الضغط",
    category: "chest",
    primaryMuscles: ["pectoralis major"],
    secondaryMuscles: ["triceps", "core", "anterior deltoid"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "💥",
    descriptionEn: "Fundamental pushing movement requiring no equipment — train anywhere.",
    descriptionAr: "حركة ضغط أساسية لا تتطلب معدات — تدربي في أي مكان.",
    commonMistakesEn: ["Hips sagging or piking", "Partial range of motion"],
    commonMistakesAr: ["انخفاض أو ارتفاع الوركين", "مدى حركة جزئي"],
    breathingEn: "Inhale going down; exhale going up.",
    breathingAr: "شهق للأسفل؛ ازفري للأعلى.",
    beginnerTipsEn: ["Start on knees if full push-up is too hard", "Make a straight line from head to heels"],
    beginnerTipsAr: ["ابدئي على الركبتين إذا كان الضغط الكامل صعباً", "اجعلي خطاً مستقيماً من الرأس إلى الكعبين"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultDurationSec: 0,
  },

  // ─── BACK (4) ──────────────────────────────────────────────────────────────
  {
    id: "back_001",
    nameEn: "Lat Pulldown",
    nameAr: "سحب اللاتيسيموس للأسفل",
    category: "back",
    primaryMuscles: ["latissimus dorsi"],
    secondaryMuscles: ["biceps", "rear deltoid", "rhomboids"],
    equipment: ["cable"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🦸‍♀️",
    descriptionEn: "Cable pulldown to develop the lats and upper back width.",
    descriptionAr: "سحب بالكابل لتطوير عرض عضلة الظهر العريضة.",
    commonMistakesEn: ["Pulling behind the neck (neck injury risk)", "Using momentum to swing"],
    commonMistakesAr: ["السحب خلف الرقبة (خطر إصابة الرقبة)", "استخدام الزخم للتأرجح"],
    breathingEn: "Exhale as you pull down; inhale as arms extend.",
    breathingAr: "ازفري عند السحب للأسفل؛ وشهق عند امتداد الذراعين.",
    beginnerTipsEn: ["Pull to the upper chest, not behind the head", "Initiate with shoulder blades first"],
    beginnerTipsAr: ["اسحبي إلى الصدر العلوي وليس خلف الرأس", "ابدئي بلوحي الكتف أولاً"],
    videoUrl: "",
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    demoImage: require("../../../assets/images/exercises/lat-pulldown.png") as number,
    demoHint: "Pull bar to chest with a firm squeeze at the bottom",
    isTimeBased: false,
    defaultSets: 4,
    defaultReps: 10,
    defaultDurationSec: 0,
  },
  {
    id: "back_002",
    nameEn: "Seated Cable Row",
    nameAr: "التجديف بالكابل جالساً",
    category: "back",
    primaryMuscles: ["rhomboids", "trapezius", "latissimus dorsi"],
    secondaryMuscles: ["biceps", "rear deltoid"],
    equipment: ["cable"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🚣‍♀️",
    descriptionEn: "Horizontal pull targeting mid-back thickness and posture muscles.",
    descriptionAr: "سحب أفقي يستهدف سماكة منتصف الظهر وعضلات الوضعية.",
    commonMistakesEn: ["Rounding the lower back", "Shrugging the shoulders"],
    commonMistakesAr: ["تقوس أسفل الظهر", "رفع الكتفين"],
    breathingEn: "Exhale as you row; inhale as you extend arms.",
    breathingAr: "ازفري عند التجديف؛ وشهق عند امتداد الذراعين.",
    beginnerTipsEn: ["Keep chest proud throughout the pull", "Retract shoulder blades at the end"],
    beginnerTipsAr: ["ابقي صدرك منتفخاً طوال السحب", "اسحبي لوحي الكتف في النهاية"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 4,
    defaultReps: 10,
    defaultDurationSec: 0,
  },
  {
    id: "back_003",
    nameEn: "Dumbbell Romanian Deadlift",
    nameAr: "الرفعة الأرضية الرومانية بالدمبل",
    category: "back",
    primaryMuscles: ["erector spinae", "hamstrings"],
    secondaryMuscles: ["gluteus maximus", "core"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    cyclePhases: ["renewal", "power", "clarity"],
    emoji: "📏",
    descriptionEn: "Hip hinge movement stretching and loading the posterior chain.",
    descriptionAr: "حركة مفصل الورك تمد وتشحن السلسلة الخلفية.",
    commonMistakesEn: ["Rounding the lower back", "Bending the knees too much (becomes squat)"],
    commonMistakesAr: ["تقوس أسفل الظهر", "ثني الركبتين كثيراً (تصبح قرفصاء)"],
    breathingEn: "Inhale as you hinge; exhale at lockout.",
    breathingAr: "شهق عند الانحناء؛ ازفري عند الإقفال.",
    beginnerTipsEn: ["Push hips back, not down", "Feel the hamstring stretch"],
    beginnerTipsAr: ["ادفعي الوركين للخلف وليس للأسفل", "أحسسي بتمدد أوتار الركبة"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultDurationSec: 0,
  },
  {
    id: "back_004",
    nameEn: "Single-Arm Dumbbell Row",
    nameAr: "التجديف بالدمبل بذراع واحدة",
    category: "back",
    primaryMuscles: ["latissimus dorsi", "rhomboids"],
    secondaryMuscles: ["biceps", "rear deltoid", "core"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "💪",
    descriptionEn: "Unilateral row for back thickness, correcting left-right imbalances.",
    descriptionAr: "تجديف أحادي لسماكة الظهر وتصحيح اختلالات اليسار واليمين.",
    commonMistakesEn: ["Rotating the torso to row higher", "Jerking the weight"],
    commonMistakesAr: ["تدوير الجذع لرفع الوزن أعلى", "سحب الوزن بشكل متقطع"],
    breathingEn: "Exhale on the row; inhale on the way down.",
    breathingAr: "ازفري عند التجديف؛ وشهق في الطريق للأسفل.",
    beginnerTipsEn: ["Let the elbow lead the pull", "Keep hips level"],
    beginnerTipsAr: ["اتركي المرفق يقود السحب", "ابقي الوركين أفقياً"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultDurationSec: 0,
  },

  // ─── SHOULDERS (4) ─────────────────────────────────────────────────────────
  {
    id: "shoulders_001",
    nameEn: "Dumbbell Overhead Press",
    nameAr: "الضغط فوق الرأس بالدمبل",
    category: "shoulders",
    primaryMuscles: ["anterior deltoid", "lateral deltoid"],
    secondaryMuscles: ["triceps", "upper trapezius", "core"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    cyclePhases: ["power", "clarity"],
    emoji: "🙌",
    descriptionEn: "Seated or standing overhead press for shoulder size and stability.",
    descriptionAr: "ضغط فوق الرأس جالسة أو واقفة لحجم الكتف وثباته.",
    commonMistakesEn: ["Flaring ribs and arching lower back", "Pressing behind the neck"],
    commonMistakesAr: ["فتح الأضلاع وتقوس أسفل الظهر", "الضغط خلف الرقبة"],
    breathingEn: "Exhale on the press up; inhale on the way down.",
    breathingAr: "ازفري عند الضغط للأعلى؛ وشهق في الطريق للأسفل.",
    beginnerTipsEn: ["Neutral spine, no rib flare", "Use a slight incline in the early weeks"],
    beginnerTipsAr: ["عمود فقري محايد، بدون فتح الأضلاع", "استخدمي إمالة طفيفة في الأسابيع الأولى"],
    videoUrl: "",
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    demoImage: require("../../../assets/images/exercises/shoulder-press.png") as number,
    demoHint: "Press dumbbells directly overhead, keep core tight",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultDurationSec: 0,
  },
  {
    id: "shoulders_002",
    nameEn: "Lateral Raise",
    nameAr: "الرفع الجانبي",
    category: "shoulders",
    primaryMuscles: ["lateral deltoid"],
    secondaryMuscles: ["supraspinatus"],
    equipment: ["dumbbell", "cable"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🦋",
    descriptionEn: "Isolation movement for the lateral delt, creating shoulder width.",
    descriptionAr: "حركة عزل للكتف الجانبي لإنشاء عرض الكتف.",
    commonMistakesEn: ["Shrugging the traps to help lift", "Going too heavy"],
    commonMistakesAr: ["رفع العضلة الشبه منحرفة للمساعدة في الرفع", "استخدام وزن ثقيل جداً"],
    breathingEn: "Exhale on the raise; inhale on the lower.",
    breathingAr: "ازفري عند الرفع؛ وشهق عند الخفض.",
    beginnerTipsEn: ["Slight forward lean targets lateral head better", "Thumb slightly down (prone grip)"],
    beginnerTipsAr: ["ميلان طفيف للأمام يستهدف الرأس الجانبي بشكل أفضل", "إصبع الإبهام لأسفل قليلاً"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultDurationSec: 0,
  },
  {
    id: "shoulders_003",
    nameEn: "Face Pull",
    nameAr: "السحب للوجه بالكابل",
    category: "shoulders",
    primaryMuscles: ["rear deltoid", "external rotators"],
    secondaryMuscles: ["trapezius", "rhomboids"],
    equipment: ["cable"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🎯",
    descriptionEn: "Rear delt and rotator cuff exercise essential for shoulder health.",
    descriptionAr: "تمرين الكتف الخلفي والمدور أساسي لصحة الكتف.",
    commonMistakesEn: ["Pulling too low (becomes row)", "Using too much weight"],
    commonMistakesAr: ["السحب منخفضاً جداً (يصبح تجديفاً)", "استخدام وزن زائد"],
    breathingEn: "Exhale as you pull to the face.",
    breathingAr: "ازفري عند السحب للوجه.",
    beginnerTipsEn: ["Pull to forehead level, not chin", "Elbows higher than wrists at finish"],
    beginnerTipsAr: ["اسحبي إلى مستوى الجبهة وليس الذقن", "المرفقان أعلى من الرسغين عند الانتهاء"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultDurationSec: 0,
  },
  {
    id: "shoulders_004",
    nameEn: "Arnold Press",
    nameAr: "ضغط أرنولد",
    category: "shoulders",
    primaryMuscles: ["anterior deltoid", "lateral deltoid"],
    secondaryMuscles: ["triceps", "upper trapezius"],
    equipment: ["dumbbell"],
    difficulty: "intermediate",
    cyclePhases: ["renewal", "power"],
    emoji: "🎬",
    descriptionEn: "Rotating overhead press hitting all three delt heads through the range.",
    descriptionAr: "ضغط فوق الرأس الدوراني يضرب الرؤوس الثلاثة للكتف عبر المدى.",
    commonMistakesEn: ["Moving too fast through the rotation", "Losing control on the descent"],
    commonMistakesAr: ["التحرك بسرعة كبيرة خلال الدوران", "فقدان السيطرة عند النزول"],
    breathingEn: "Exhale as you press and rotate.",
    breathingAr: "ازفري عند الضغط والدوران.",
    beginnerTipsEn: ["Go lighter than a normal press to nail the rotation", "Controlled 3-second descent"],
    beginnerTipsAr: ["استخدمي وزناً أخف من الضغط العادي", "نزول متحكم به لمدة 3 ثوانٍ"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultDurationSec: 0,
  },

  // ─── ARMS (4) ──────────────────────────────────────────────────────────────
  {
    id: "arms_001",
    nameEn: "Barbell Curl",
    nameAr: "تجعيد البايسبس بالبار",
    category: "arms",
    primaryMuscles: ["biceps brachii"],
    secondaryMuscles: ["brachialis", "forearms"],
    equipment: ["barbell"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "💪",
    descriptionEn: "Classic biceps curl for arm size and strength.",
    descriptionAr: "تجعيد البايسبس الكلاسيكي لحجم الذراع وقوتها.",
    commonMistakesEn: ["Swinging the body to lift", "Not fully extending at the bottom"],
    commonMistakesAr: ["تأرجح الجسم للرفع", "عدم الامتداد الكامل في الأسفل"],
    breathingEn: "Exhale on the curl up; inhale on the way down.",
    breathingAr: "ازفري عند التجعيد للأعلى؛ وشهق في الطريق للأسفل.",
    beginnerTipsEn: ["Keep elbows pinned to sides", "Use EZ bar to reduce wrist stress"],
    beginnerTipsAr: ["اثبتي المرفقين على الجانبين", "استخدمي بار EZ لتقليل ضغط الرسغ"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultDurationSec: 0,
  },
  {
    id: "arms_002",
    nameEn: "Triceps Pushdown",
    nameAr: "ضغط الترايسبس بالكابل",
    category: "arms",
    primaryMuscles: ["triceps brachii"],
    secondaryMuscles: [],
    equipment: ["cable"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "⬇️",
    descriptionEn: "Cable isolation exercise for triceps mass and definition.",
    descriptionAr: "تمرين عزل بالكابل لحجم الترايسبس وتحديده.",
    commonMistakesEn: ["Flaring elbows out", "Leaning too far forward"],
    commonMistakesAr: ["فتح المرفقين للخارج", "الانحناء للأمام كثيراً"],
    breathingEn: "Exhale on the push down.",
    breathingAr: "ازفري عند الضغط للأسفل.",
    beginnerTipsEn: ["Keep upper arms vertical", "Fully extend at the bottom"],
    beginnerTipsAr: ["ابقي الذراعين العلويتين عمودياً", "امتدادي بالكامل في الأسفل"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultDurationSec: 0,
  },
  {
    id: "arms_003",
    nameEn: "Hammer Curl",
    nameAr: "تجعيد المطرقة",
    category: "arms",
    primaryMuscles: ["brachialis", "brachioradialis"],
    secondaryMuscles: ["biceps brachii"],
    equipment: ["dumbbell"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🔨",
    descriptionEn: "Neutral-grip curl targeting the brachialis for arm thickness.",
    descriptionAr: "تجعيد بقبضة محايدة يستهدف العضلة العضدية لسماكة الذراع.",
    commonMistakesEn: ["Rotating the wrist (becomes regular curl)", "Short range of motion"],
    commonMistakesAr: ["تدوير الرسغ (يصبح تجعيداً عادياً)", "مدى حركة قصير"],
    breathingEn: "Exhale on the curl.",
    breathingAr: "ازفري عند التجعيد.",
    beginnerTipsEn: ["Palms face each other throughout the movement", "Alternate arms for more control"],
    beginnerTipsAr: ["راحتا اليدين تواجهان بعضهما طوال الحركة", "بادلي الذراعين لمزيد من التحكم"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultDurationSec: 0,
  },
  {
    id: "arms_004",
    nameEn: "Overhead Triceps Extension",
    nameAr: "تمديد الترايسبس فوق الرأس",
    category: "arms",
    primaryMuscles: ["triceps brachii (long head)"],
    secondaryMuscles: [],
    equipment: ["dumbbell", "cable"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🙆‍♀️",
    descriptionEn: "Overhead extension hitting the long head of the triceps in a stretched position.",
    descriptionAr: "تمديد علوي يضرب الرأس الطويل للترايسبس في وضع ممدد.",
    commonMistakesEn: ["Flaring elbows outward", "Short range at the top"],
    commonMistakesAr: ["فتح المرفقين للخارج", "مدى قصير في الأعلى"],
    breathingEn: "Exhale as you extend the arms.",
    breathingAr: "ازفري عند تمديد الذراعين.",
    beginnerTipsEn: ["Keep elbows close to the head", "Full stretch at the bottom is key"],
    beginnerTipsAr: ["ابقي المرفقين قريبة من الرأس", "التمدد الكامل في الأسفل هو المفتاح"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultDurationSec: 0,
  },

  // ─── CORE (4) ──────────────────────────────────────────────────────────────
  {
    id: "core_001",
    nameEn: "Dead Bug",
    nameAr: "الخنفساء الميتة",
    category: "core",
    primaryMuscles: ["transverse abdominis", "rectus abdominis"],
    secondaryMuscles: ["hip flexors"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🪲",
    descriptionEn: "Anti-extension core exercise safe for all cycle phases and beginners.",
    descriptionAr: "تمرين مضاد للامتداد آمن لجميع مراحل الدورة والمبتدئين.",
    commonMistakesEn: ["Lower back lifting off the floor", "Holding the breath"],
    commonMistakesAr: ["ارتفاع أسفل الظهر عن الأرض", "حبس النفس"],
    breathingEn: "Exhale fully before extending limbs; maintain the exhale.",
    breathingAr: "ازفري بالكامل قبل تمديد الأطراف؛ حافظي على الزفير.",
    beginnerTipsEn: ["Press lower back flat to floor throughout", "Start with small ranges"],
    beginnerTipsAr: ["اضغطي أسفل الظهر مسطحاً على الأرض طوال الوقت", "ابدئي بمدى حركة صغير"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 3,
    defaultReps: 0,
    defaultDurationSec: 30,
  },
  {
    id: "core_002",
    nameEn: "Cable Woodchop",
    nameAr: "قطع الخشب بالكابل",
    category: "core",
    primaryMuscles: ["obliques", "transverse abdominis"],
    secondaryMuscles: ["shoulders", "glutes"],
    equipment: ["cable"],
    difficulty: "intermediate",
    cyclePhases: ["power", "clarity"],
    emoji: "🪵",
    descriptionEn: "Rotational core movement mimicking real-world anti-rotation demands.",
    descriptionAr: "حركة دورانية للجوهر تحاكي متطلبات مقاومة الدوران الحقيقية.",
    commonMistakesEn: ["Using the arms instead of the core to rotate", "Feet moving"],
    commonMistakesAr: ["استخدام الذراعين بدلاً من الجوهر للدوران", "تحريك القدمين"],
    breathingEn: "Exhale sharply as you chop across.",
    breathingAr: "ازفري بشكل حاد عند القطع.",
    beginnerTipsEn: ["Pivot the trail foot to protect the knee", "Control the return slowly"],
    beginnerTipsAr: ["أديري القدم الخلفية لحماية الركبة", "تحكمي في العودة ببطء"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultDurationSec: 0,
  },
  {
    id: "core_003",
    nameEn: "Plank",
    nameAr: "تمرين البلانك",
    category: "core",
    primaryMuscles: ["transverse abdominis", "rectus abdominis"],
    secondaryMuscles: ["glutes", "shoulders", "quads"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🪨",
    descriptionEn: "Full-body isometric bracing that builds a resilient core.",
    descriptionAr: "تثبيت متساوٍ كامل الجسم يبني جوهراً مرناً.",
    commonMistakesEn: ["Hips too high or too low", "Holding the breath"],
    commonMistakesAr: ["الوركان عاليان جداً أو منخفضان جداً", "حبس النفس"],
    breathingEn: "Breathe normally throughout.",
    breathingAr: "تنفسي بشكل طبيعي طوال التمرين.",
    beginnerTipsEn: ["Squeeze glutes, quads, and abs simultaneously", "Look at the floor to keep neutral neck"],
    beginnerTipsAr: ["اضغطي الألية والرباعية والبطن في نفس الوقت", "انظري للأرض للحفاظ على الرقبة محايدة"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 3,
    defaultReps: 0,
    defaultDurationSec: 45,
  },
  {
    id: "core_004",
    nameEn: "Ab Wheel Rollout",
    nameAr: "لفة عجلة البطن",
    category: "core",
    primaryMuscles: ["rectus abdominis", "transverse abdominis"],
    secondaryMuscles: ["lats", "shoulders"],
    equipment: ["bodyweight"],
    difficulty: "advanced",
    cyclePhases: ["power", "clarity"],
    emoji: "🎡",
    descriptionEn: "Advanced anti-extension movement requiring strong core integrity.",
    descriptionAr: "حركة متقدمة مضادة للامتداد تتطلب قوة جوهرية قوية.",
    commonMistakesEn: ["Hips sagging on the rollout", "Rolling too far before building strength"],
    commonMistakesAr: ["انخفاض الوركين عند اللف", "اللف لمسافة بعيدة جداً قبل بناء القوة"],
    breathingEn: "Exhale as you roll out; inhale on the way back.",
    breathingAr: "ازفري عند اللف للخارج؛ وشهق عند العودة.",
    beginnerTipsEn: ["Start with partial rollouts", "Engage your lats to pull back"],
    beginnerTipsAr: ["ابدئي بلفات جزئية", "استخدمي عضلات الظهر للسحب للخلف"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 3,
    defaultReps: 8,
    defaultDurationSec: 0,
  },

  // ─── MOBILITY (4) ──────────────────────────────────────────────────────────
  {
    id: "mobility_001",
    nameEn: "World's Greatest Stretch",
    nameAr: "أعظم تمدد في العالم",
    category: "mobility",
    primaryMuscles: ["hip flexors", "thoracic spine", "glutes"],
    secondaryMuscles: ["hamstrings", "adductors", "ankles"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🌍",
    descriptionEn: "Multi-joint mobility flow hitting hips, thoracic, and ankles together.",
    descriptionAr: "تدفق متعدد المفاصل للحركة يصل الوركين والظهر الصدري والكاحلين معاً.",
    commonMistakesEn: ["Rushing through the movement", "Not fully rotating the thoracic"],
    commonMistakesAr: ["الإسراع في الحركة", "عدم التدوير الكامل للمنطقة الصدرية"],
    breathingEn: "Exhale into each rotation.",
    breathingAr: "ازفري في كل دوران.",
    beginnerTipsEn: ["Do 5 reps each side as a warm-up", "Use a wall for thoracic rotation support"],
    beginnerTipsAr: ["افعلي 5 تكرارات لكل جانب كإحماء", "استخدمي الحائط لدعم الدوران الصدري"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 2,
    defaultReps: 5,
    defaultDurationSec: 0,
  },
  {
    id: "mobility_002",
    nameEn: "Hip 90/90 Stretch",
    nameAr: "تمدد الورك 90/90",
    category: "mobility",
    primaryMuscles: ["hip external rotators", "hip internal rotators"],
    secondaryMuscles: ["glutes", "piriformis"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🔄",
    descriptionEn: "Seated hip position that simultaneously stretches both rotation directions.",
    descriptionAr: "وضعية الورك جالسة تمد اتجاهي الدوران في نفس الوقت.",
    commonMistakesEn: ["Leaning too far forward from the hips", "Sitting on an uneven pelvis"],
    commonMistakesAr: ["الميل للأمام كثيراً من الوركين", "الجلوس على حوض غير متساوٍ"],
    breathingEn: "Take slow, deep breaths into the stretch.",
    breathingAr: "خذي أنفاساً بطيئة وعميقة في التمدد.",
    beginnerTipsEn: ["Sit on a folded blanket if hips are tight", "Hold each side for 60–90 seconds"],
    beginnerTipsAr: ["اجلسي على بطانية مطوية إذا كانت الوركان متصلبة", "احتفظي بكل جانب لمدة 60-90 ثانية"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 2,
    defaultReps: 0,
    defaultDurationSec: 60,
  },
  {
    id: "mobility_003",
    nameEn: "Cat-Cow",
    nameAr: "تمرين القطة والبقرة",
    category: "mobility",
    primaryMuscles: ["erector spinae", "multifidus"],
    secondaryMuscles: ["core"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🐱",
    descriptionEn: "Spinal flexion-extension flow that relieves lower back tension.",
    descriptionAr: "تدفق ثني وتمديد العمود الفقري يخفف من توتر أسفل الظهر.",
    commonMistakesEn: ["Moving only the lumbar (should involve thoracic too)", "Holding breath"],
    commonMistakesAr: ["تحريك أسفل الظهر فقط (يجب أن يشمل الصدري أيضاً)", "حبس النفس"],
    breathingEn: "Inhale into the cow position; exhale into the cat position.",
    breathingAr: "شهق في وضع البقرة؛ وازفري في وضع القطة.",
    beginnerTipsEn: ["Move slowly, one vertebra at a time", "Great for menstrual phase"],
    beginnerTipsAr: ["تحركي ببطء، فقرة بفقرة", "ممتازة لمرحلة الحيض"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 2,
    defaultReps: 10,
    defaultDurationSec: 0,
  },
  {
    id: "mobility_004",
    nameEn: "Ankle Circles",
    nameAr: "دوائر الكاحل",
    category: "mobility",
    primaryMuscles: ["ankle stabilizers"],
    secondaryMuscles: ["calves"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "⭕",
    descriptionEn: "Circular ankle mobility drill — essential before leg day or cardio.",
    descriptionAr: "تمرين حركة الكاحل الدائري — ضروري قبل يوم الساق أو الكارديو.",
    commonMistakesEn: ["Moving only in one plane", "Too fast to feel the range"],
    commonMistakesAr: ["التحرك في مستوى واحد فقط", "السرعة الزائدة دون الشعور بالمدى"],
    breathingEn: "Breathe naturally.",
    breathingAr: "تنفسي بشكل طبيعي.",
    beginnerTipsEn: ["10 slow circles in each direction per foot", "Use as a daily morning ritual"],
    beginnerTipsAr: ["10 دوائر بطيئة في كل اتجاه لكل قدم", "استخدميها كطقوس صباحية يومية"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 2,
    defaultReps: 10,
    defaultDurationSec: 0,
  },

  // ─── CARDIO (4) ────────────────────────────────────────────────────────────
  {
    id: "cardio_001",
    nameEn: "Jump Rope",
    nameAr: "تخطي الحبل",
    category: "cardio",
    primaryMuscles: ["calves", "shoulders"],
    secondaryMuscles: ["core", "quads"],
    equipment: ["none"],
    difficulty: "beginner",
    cyclePhases: ["renewal", "power", "clarity"],
    emoji: "🪢",
    descriptionEn: "High-efficiency cardio tool improving coordination, timing, and stamina.",
    descriptionAr: "أداة كارديو عالية الكفاءة تحسن التنسيق والتوقيت والتحمل.",
    commonMistakesEn: ["Jumping too high", "Using arms too wide"],
    commonMistakesAr: ["القفز عالياً جداً", "استخدام الذراعين بشكل واسع جداً"],
    breathingEn: "Find a rhythm with your breathing.",
    breathingAr: "اجدي إيقاعاً مع تنفسك.",
    beginnerTipsEn: ["Start with 30-second intervals", "Land softly on the balls of your feet"],
    beginnerTipsAr: ["ابدئي بفترات 30 ثانية", "اهبطي بلطف على مقدمة قدميك"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 5,
    defaultReps: 0,
    defaultDurationSec: 60,
  },
  {
    id: "cardio_002",
    nameEn: "Stair Climber",
    nameAr: "صاعدة السلالم",
    category: "cardio",
    primaryMuscles: ["quads", "gluteus maximus"],
    secondaryMuscles: ["hamstrings", "calves", "core"],
    equipment: ["machine"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🪜",
    descriptionEn: "Low-impact cardio on the stair machine that doubles as a glute activator.",
    descriptionAr: "كارديو منخفض التأثير على آلة السلالم تعمل أيضاً كمنشط للألية.",
    commonMistakesEn: ["Leaning heavily on the handles", "Setting speed too high to maintain form"],
    commonMistakesAr: ["الاتكاء بشكل كبير على المقابض", "ضبط سرعة عالية جداً"],
    breathingEn: "Maintain steady rhythmic breathing.",
    breathingAr: "حافظي على تنفس إيقاعي ثابت.",
    beginnerTipsEn: ["Lightly touch the rails for balance only", "Lean slightly forward from the hips"],
    beginnerTipsAr: ["المسي القضبان بلطف للتوازن فقط", "انحني قليلاً للأمام من الوركين"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 1,
    defaultReps: 0,
    defaultDurationSec: 1200,
  },
  {
    id: "cardio_003",
    nameEn: "Rowing Machine",
    nameAr: "آلة التجديف",
    category: "cardio",
    primaryMuscles: ["back", "legs"],
    secondaryMuscles: ["core", "arms", "shoulders"],
    equipment: ["machine"],
    difficulty: "beginner",
    cyclePhases: ["renewal", "power", "clarity"],
    emoji: "🚣‍♀️",
    descriptionEn: "Full-body cardio with 60% legs and 40% upper body emphasis.",
    descriptionAr: "كارديو كامل الجسم بتأكيد 60% على الساقين و40% على الجزء العلوي.",
    commonMistakesEn: ["Arm-dominant rowing (should start with legs)", "Rounded lower back"],
    commonMistakesAr: ["التجديف بالذراعين (يجب أن يبدأ بالساقين)", "تقوس أسفل الظهر"],
    breathingEn: "Exhale on the drive; inhale on the recovery.",
    breathingAr: "ازفري عند الدفع؛ وشهق عند الاسترداد.",
    beginnerTipsEn: ["Sequence: legs → lean → arms (and reverse)", "Rate 18–22 spm for endurance"],
    beginnerTipsAr: ["التسلسل: الساقين → الانحناء → الذراعين (والعكس)", "معدل 18-22 ضربة/دقيقة للتحمل"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 1,
    defaultReps: 0,
    defaultDurationSec: 1200,
  },
  {
    id: "cardio_004",
    nameEn: "HIIT Sprints",
    nameAr: "سباقات التدريب المتقطع عالي الكثافة",
    category: "cardio",
    primaryMuscles: ["quads", "hamstrings", "calves"],
    secondaryMuscles: ["core", "glutes"],
    equipment: ["none"],
    difficulty: "intermediate",
    cyclePhases: ["power"],
    emoji: "⚡",
    descriptionEn: "Short maximal effort sprints with rest periods for peak metabolic conditioning.",
    descriptionAr: "جري سريع قصير بأقصى جهد مع فترات راحة لذروة اللياقة الأيضية.",
    commonMistakesEn: ["Not resting enough between intervals", "Poor warm-up before max effort"],
    commonMistakesAr: ["عدم الراحة الكافية بين الفترات", "إحماء ضعيف قبل الجهد الأقصى"],
    breathingEn: "Sprint hard; recover with slow nasal breathing.",
    breathingAr: "اجري بقوة؛ استردي بتنفس أنفي بطيء.",
    beginnerTipsEn: ["Start with 10s sprint / 50s rest ratios", "Best during ovulation phase"],
    beginnerTipsAr: ["ابدئي بنسبة 10 ثانية جري / 50 ثانية راحة", "الأفضل في مرحلة التبويض"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 8,
    defaultReps: 0,
    defaultDurationSec: 10,
  },

  // ─── STRETCHING (6) ───────────────────────────────────────────────────────
  {
    id: "stretch_001",
    nameEn: "Standing Hamstring Stretch",
    nameAr: "تمدد أوتار الركبة وقوفاً",
    category: "stretching",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["lower back", "calves"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🙆‍♀️",
    descriptionEn: "Static hamstring stretch held at the end of range to improve flexibility.",
    descriptionAr: "تمدد ثابت لأوتار الركبة عند نهاية المدى لتحسين المرونة.",
    commonMistakesEn: ["Bending the knee too much", "Rounding the spine instead of hinging at the hip"],
    commonMistakesAr: ["ثني الركبة أكثر من اللازم", "تقريس العمود الفقري بدلاً من المفصلة من الورك"],
    breathingEn: "Inhale to prepare; exhale to deepen the stretch.",
    breathingAr: "شهق للتحضير؛ ازفري للتعمق في التمدد.",
    beginnerTipsEn: ["Hinge forward from the hip, not the waist", "Hold for 30–60 seconds per side"],
    beginnerTipsAr: ["انحني من الورك وليس من الخصر", "احتفظي 30-60 ثانية لكل جانب"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 2,
    defaultReps: 0,
    defaultDurationSec: 45,
  },
  {
    id: "stretch_002",
    nameEn: "Hip Flexor Lunge Stretch",
    nameAr: "تمدد عضلة الفخذ الأمامية بالانقسام",
    category: "stretching",
    primaryMuscles: ["hip flexors", "psoas"],
    secondaryMuscles: ["quadriceps"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🤸‍♀️",
    descriptionEn: "Deep lunge that opens up tight hip flexors and counteracts desk posture.",
    descriptionAr: "انقسام عميق يفتح عضلات الفخذ الأمامية المشدودة ويعكس وضعية المكتب.",
    commonMistakesEn: ["Letting the front knee collapse inward", "Not squeezing the rear glute"],
    commonMistakesAr: ["ترك الركبة الأمامية تنهار للداخل", "عدم ضغط الألية الخلفية"],
    breathingEn: "Exhale and sink deeper with each breath.",
    breathingAr: "ازفري وانحدري بشكل أعمق مع كل نفس.",
    beginnerTipsEn: ["Start with a half-kneeling position", "Squeeze the rear glute to maximise the stretch"],
    beginnerTipsAr: ["ابدئي بوضعية الركبة نصف المثنية", "اضغطي الألية الخلفية لتعظيم التمدد"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 2,
    defaultReps: 0,
    defaultDurationSec: 45,
  },
  {
    id: "stretch_003",
    nameEn: "Doorway Chest Stretch",
    nameAr: "تمدد الصدر بالباب",
    category: "stretching",
    primaryMuscles: ["pectoralis major", "anterior deltoid"],
    secondaryMuscles: ["biceps"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🚪",
    descriptionEn: "Doorframe-assisted chest opener reversing rounded-shoulder posture.",
    descriptionAr: "فتح الصدر بمساعدة إطار الباب لعكس وضعية الكتفين المستديرة.",
    commonMistakesEn: ["Pushing forward aggressively", "Lifting the chin and compressing the neck"],
    commonMistakesAr: ["الدفع للأمام بقوة", "رفع الذقن وضغط الرقبة"],
    breathingEn: "Breathe slowly into the chest as you open.",
    breathingAr: "تنفسي ببطء في الصدر عند الفتح.",
    beginnerTipsEn: ["Set elbow at 90° for a safer stretch", "Move one foot forward to increase intensity"],
    beginnerTipsAr: ["ضعي المرفق عند 90° لتمدد أكثر أماناً", "قدمي قدماً للأمام لزيادة الشدة"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 2,
    defaultReps: 0,
    defaultDurationSec: 30,
  },
  {
    id: "stretch_004",
    nameEn: "Pigeon Pose",
    nameAr: "وضعية الحمامة",
    category: "stretching",
    primaryMuscles: ["piriformis", "glutes", "hip external rotators"],
    secondaryMuscles: ["hip flexors", "groin"],
    equipment: ["bodyweight"],
    difficulty: "intermediate",
    cyclePhases: ["menstrual", "calm", "all"],
    emoji: "🕊️",
    descriptionEn: "Deep hip-opener targeting the piriformis and posterior glute — essential for sciatica relief.",
    descriptionAr: "فتح عميق للورك يستهدف العضلة الكمثرية والألية الخلفية — أساسي لتخفيف آلام عرق النسا.",
    commonMistakesEn: ["Letting the hips twist to one side", "Forcing depth before you're ready"],
    commonMistakesAr: ["ترك الوركين يلتويان لأحد الجانبين", "إجبار العمق قبل الاستعداد"],
    breathingEn: "Slow diaphragmatic breaths to relax into the pose.",
    breathingAr: "أنفاس حجابية بطيئة للاسترخاء في الوضعية.",
    beginnerTipsEn: ["Use a folded blanket under the front hip if needed", "Hold 90 seconds to allow the nervous system to release"],
    beginnerTipsAr: ["استخدمي بطانية مطوية تحت الورك الأمامي عند الحاجة", "احتفظي 90 ثانية لإتاحة الفرصة للجهاز العصبي للتحرر"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 2,
    defaultReps: 0,
    defaultDurationSec: 90,
  },
  {
    id: "stretch_005",
    nameEn: "Seated Spinal Twist",
    nameAr: "الالتواء الشوكي الجالس",
    category: "stretching",
    primaryMuscles: ["thoracic rotators", "obliques"],
    secondaryMuscles: ["glutes", "neck"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🌀",
    descriptionEn: "Seated rotation that mobilises the thoracic spine and relieves tension from sitting.",
    descriptionAr: "دوران جالس يحرك الفقرات الصدرية ويخفف التوتر من الجلوس.",
    commonMistakesEn: ["Twisting from the lumbar spine instead of the thoracic", "Forcing the twist with the arm"],
    commonMistakesAr: ["الالتواء من الفقرات القطنية بدلاً من الصدرية", "إجبار الالتواء بالذراع"],
    breathingEn: "Inhale to lengthen the spine; exhale to rotate further.",
    breathingAr: "شهق لإطالة العمود الفقري؛ ازفري للدوران أبعد.",
    beginnerTipsEn: ["Sit tall before twisting", "Look over the back shoulder to complete the rotation"],
    beginnerTipsAr: ["اجلسي مستقيمة قبل الالتواء", "انظري فوق الكتف الخلفي لإتمام الدوران"],
    videoUrl: "",
    isTimeBased: false,
    defaultSets: 2,
    defaultReps: 10,
    defaultDurationSec: 0,
  },
  {
    id: "stretch_006",
    nameEn: "Overhead Tricep Stretch",
    nameAr: "تمدد العضلة ثلاثية الرؤوس فوق الرأس",
    category: "stretching",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["latissimus dorsi", "shoulder"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🙌",
    descriptionEn: "Standing arm stretch targeting the long head of the tricep and lat insertion.",
    descriptionAr: "تمدد ذراع وقوفاً يستهدف الرأس الطويل للعضلة ثلاثية الرؤوس وامتداد الظهر العريض.",
    commonMistakesEn: ["Flaring the ribs out", "Pulling the elbow forcefully"],
    commonMistakesAr: ["انتشار الأضلاع للخارج", "سحب المرفق بقوة"],
    breathingEn: "Exhale as you gently pull the elbow behind the head.",
    breathingAr: "ازفري عند سحب المرفق بلطف خلف الرأس.",
    beginnerTipsEn: ["Use the opposite hand to gently guide the stretch", "Keep ribs down and core engaged"],
    beginnerTipsAr: ["استخدمي اليد المقابلة لتوجيه التمدد بلطف", "أبقي الأضلاع للأسفل والجوهر منشطاً"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 2,
    defaultReps: 0,
    defaultDurationSec: 30,
  },

  // ─── RECOVERY (6) ──────────────────────────────────────────────────────────
  {
    id: "recovery_001",
    nameEn: "Foam Roll Quads",
    nameAr: "تدليك الرباعية بالأسطوانة",
    category: "recovery",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["IT band"],
    equipment: ["foam_roller"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🛞",
    descriptionEn: "Self-myofascial release for quad tension after leg training.",
    descriptionAr: "إفراج ذاتي للعضلة اللفافية لتوتر الرباعية بعد تدريب الساق.",
    commonMistakesEn: ["Rolling over joints (knee, hip)", "Going too fast"],
    commonMistakesAr: ["تدليك فوق المفاصل (الركبة، الورك)", "التحرك بسرعة كبيرة"],
    breathingEn: "Breathe deeply into tender spots.",
    breathingAr: "تنفسي بعمق في نقاط الحساسية.",
    beginnerTipsEn: ["Pause 30–45s on tender spots", "Avoid rolling directly on the IT band"],
    beginnerTipsAr: ["توقفي 30-45 ثانية على نقاط الحساسية", "تجنبي التدليك مباشرة على الفرقة الوترية"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 1,
    defaultReps: 0,
    defaultDurationSec: 90,
  },
  {
    id: "recovery_002",
    nameEn: "Child's Pose",
    nameAr: "وضعية الطفل",
    category: "recovery",
    primaryMuscles: ["lower back", "hip flexors", "glutes"],
    secondaryMuscles: ["ankles"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["menstrual", "calm", "all"],
    emoji: "🧘‍♀️",
    descriptionEn: "Passive stretch relieving lower back and hip tension, calming the nervous system.",
    descriptionAr: "تمدد سلبي يخفف توتر أسفل الظهر والورك، ويهدئ الجهاز العصبي.",
    commonMistakesEn: ["Forcing the stretch when fatigued", "Holding shoulders tense"],
    commonMistakesAr: ["إجبار التمدد عند التعب", "إبقاء الكتفين متوترتين"],
    breathingEn: "Long slow exhales through the mouth.",
    breathingAr: "زفير بطيء طويل من الفم.",
    beginnerTipsEn: ["Use a pillow under the knees if needed", "Great on rest days and during menstrual phase"],
    beginnerTipsAr: ["استخدمي وسادة تحت الركبتين عند الحاجة", "ممتازة في أيام الراحة ومرحلة الحيض"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 1,
    defaultReps: 0,
    defaultDurationSec: 120,
  },
  {
    id: "recovery_003",
    nameEn: "Diaphragmatic Breathing",
    nameAr: "التنفس الحجابي",
    category: "recovery",
    primaryMuscles: ["diaphragm", "core"],
    secondaryMuscles: [],
    equipment: ["none"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🫁",
    descriptionEn: "Parasympathetic breathing technique that lowers cortisol and improves HRV.",
    descriptionAr: "تقنية تنفس نظير الودي تخفض الكورتيزول وتحسن HRV.",
    commonMistakesEn: ["Chest breathing instead of belly breathing", "Forcing the breath rhythm"],
    commonMistakesAr: ["التنفس الصدري بدلاً من التنفس البطني", "إجبار إيقاع النفس"],
    breathingEn: "4-count inhale, 4-count hold, 6-count exhale.",
    breathingAr: "شهق لعدد 4، انتظار لعدد 4، زفير لعدد 6.",
    beginnerTipsEn: ["Place one hand on chest, one on belly — only the belly should rise", "Practice 5 minutes before sleep"],
    beginnerTipsAr: ["ضعي يداً على الصدر ويداً على البطن — يجب أن ترتفع البطن فقط", "مارسيها 5 دقائق قبل النوم"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 1,
    defaultReps: 0,
    defaultDurationSec: 300,
  },
  {
    id: "recovery_004",
    nameEn: "Supine Spinal Twist",
    nameAr: "الالتواء الشوكي الاستلقائي",
    category: "recovery",
    primaryMuscles: ["thoracic rotators", "glutes", "piriformis"],
    secondaryMuscles: ["obliques"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["menstrual", "calm", "all"],
    emoji: "🔀",
    descriptionEn: "Lying rotation decompressing the lumbar and thoracic spine.",
    descriptionAr: "دوران مستلقٍ يفك ضغط العمود الفقري القطني والصدري.",
    commonMistakesEn: ["Forcing the shoulder down forcefully", "Rushing the movement"],
    commonMistakesAr: ["إجبار الكتف للأسفل بقوة", "الإسراع في الحركة"],
    breathingEn: "Exhale and melt deeper into the twist with each breath.",
    breathingAr: "ازفري وذوبي أعمق في الالتواء مع كل نفس.",
    beginnerTipsEn: ["Use a pillow under the knee if hip is tight", "Hold 60–90 seconds per side"],
    beginnerTipsAr: ["استخدمي وسادة تحت الركبة إذا كان الورك متصلباً", "احتفظي بالوضعية 60-90 ثانية لكل جانب"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 2,
    defaultReps: 0,
    defaultDurationSec: 60,
  },
  {
    id: "recovery_005",
    nameEn: "Foam Roll Upper Back",
    nameAr: "تدليك الظهر العلوي بالأسطوانة",
    category: "recovery",
    primaryMuscles: ["thoracic spine", "rhomboids"],
    secondaryMuscles: ["trapezius"],
    equipment: ["foam_roller"],
    difficulty: "beginner",
    cyclePhases: ["all"],
    emoji: "🫱",
    descriptionEn: "Thoracic extension and myofascial release to reverse desk posture.",
    descriptionAr: "تمديد صدري وإفراج للعضلة اللفافية لعكس وضعية المكتب.",
    commonMistakesEn: ["Rolling onto the lower back", "Going too fast"],
    commonMistakesAr: ["التدليك على أسفل الظهر", "التحرك بسرعة كبيرة"],
    breathingEn: "Exhale as you extend over the roller.",
    breathingAr: "ازفري عند الامتداد فوق الأسطوانة.",
    beginnerTipsEn: ["Start at mid-back, stop at the base of the neck", "Open arms to the side to spread shoulder blades"],
    beginnerTipsAr: ["ابدئي من وسط الظهر، توقفي عند قاعدة الرقبة", "افتحي الذراعين للجانب لفتح لوحي الكتف"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 1,
    defaultReps: 0,
    defaultDurationSec: 90,
  },
  {
    id: "recovery_006",
    nameEn: "Legs Up the Wall",
    nameAr: "الساقان على الحائط",
    category: "recovery",
    primaryMuscles: ["lower back", "hamstrings"],
    secondaryMuscles: ["calves"],
    equipment: ["bodyweight"],
    difficulty: "beginner",
    cyclePhases: ["menstrual", "calm"],
    emoji: "🧘",
    descriptionEn: "Passive inversion restorative pose that drains leg fatigue and calms the nervous system.",
    descriptionAr: "وضعية انقلاب سلبية تستنزف إرهاق الساق وتهدئ الجهاز العصبي.",
    commonMistakesEn: ["Not getting close enough to the wall", "Tensing the hips"],
    commonMistakesAr: ["عدم الاقتراب الكافي من الحائط", "توتر الوركين"],
    breathingEn: "Deep diaphragmatic breathing throughout.",
    breathingAr: "تنفس حجابي عميق طوال الوقت.",
    beginnerTipsEn: ["5–10 minutes is ideal for recovery", "Best for the evening after hard training"],
    beginnerTipsAr: ["5-10 دقائق مثالية للتعافي", "الأفضل في المساء بعد التدريب الشاق"],
    videoUrl: "",
    isTimeBased: true,
    defaultSets: 1,
    defaultReps: 0,
    defaultDurationSec: 300,
  },
];

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISE_DATABASE.find((e) => e.id === id);
}

export function getExercisesByCategory(category: string): Exercise[] {
  return EXERCISE_DATABASE.filter((e) => e.category === category);
}

export function getExercisesByPhase(phase: string): Exercise[] {
  return EXERCISE_DATABASE.filter(
    (e) => e.cyclePhases.includes("all") || e.cyclePhases.includes(phase as any)
  );
}

export function searchExercises(query: string, opts?: {
  difficulty?: string;
  equipment?: string;
}): Exercise[] {
  let results = EXERCISE_DATABASE;

  const diff = opts?.difficulty;
  const equip = opts?.equipment;

  if (diff && diff !== "all") {
    results = results.filter((e) => e.difficulty === diff);
  }
  if (equip && equip !== "all") {
    results = results.filter((e) => e.equipment.includes(equip as any));
  }

  if (!query.trim()) return results;

  const q = query.toLowerCase().trim();
  return results.filter(
    (e) =>
      e.nameEn.toLowerCase().includes(q) ||
      e.nameAr.includes(q) ||
      e.primaryMuscles.some((m) => m.toLowerCase().includes(q)) ||
      e.secondaryMuscles.some((m) => m.toLowerCase().includes(q)) ||
      e.category.toLowerCase().includes(q) ||
      e.equipment.some((eq) => eq.toLowerCase().includes(q)) ||
      e.difficulty.toLowerCase().includes(q)
  );
}
